# -*- coding: utf-8 -*-
"""machine_learning_python_project_one_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vymBlM0bsoutqgEDGosRIRghb6GK2ZN-
"""

import numpy as np
import pandas as pd
import scipy as sp
import scipy.stats as stats